# chapter3
```{r echo=FALSE}
library('tm')
library('ggplot2')
```

## 分類について
決定境界
* 非線形なものも含む分離超平面  
* 複数の線が引けるものも含む

カーネルトリック
* 計算コストをほとんど増加させずに高度な境界決定を行う手法

## 分類の事例
測定変数(素性、予測因子)からラベル(クラス、タイプ)の推定を行う
* 性別から身長と体重(前章の例)
* マンモグラフィの結果から乳がんであるか
* 血圧測定から高血圧であるか
* 選挙候補者の政治的立場から政党を予測
* SNSの画像に顔がうつっているか
* 著書から作者予測

## テキスト分類によるメールのスパム判定
電子メールのプレーンテキストを使うため、素性への変換が必要となる  
スパム/非スパムを0/1に符号化し、テキストに含まれる単語ごとに、  
その単語が含まれる場合どちらである確率が高いかなど計算できる形式に変換する

素性に何を選ぶかは機械学習における重要な研究トピックの一つ  
自動化はできていない  
経験を積もう

### テキストマイニング用パッケージの使用
※英語のみ。日本語を扱うにはRMeCabなどが必要

単語の出現回数カウントを素性として扱う

単語   | スパム | 非スパム
-------|--------|---------
html   |  377   |   9
tabble |  1182  |  43

のような形式の場合これらはスパムの方に多く出現し、非スパムにはあまり出現しないため、  
スパムである傾向が強い

プロットしたときに多くの点が重なってしまう場合はランダムノイズ(ジッタ)を加える
(後で図)

実際には単語以外にも有効な素性として
* 偽装ヘッダ
* IP
* ブラックリスト

何どあるが、メールの数が十分に多ければそれだけでもそこそこの精度になるため今回は扱わない

### 条件付き確率
既に知っているものをベースに確率をだすもの  

ex:あるコンピュータサイエンスの学生が女性である確率を知りたい
* 所属する大学の学部全体は51%が女性
* コンピュータサイエンス全体では22%が女性  

所属の情報を入れることで51%から22%まで下がる

ナイーブベイズ  
観測されたデータから
* 明らかにスパムに出現しやすい
* 明らかに非スパムに出現しやすい

の差異を発見する

あとから与えられたデータがどちらに出現しやすいかで予測が行える  
スパムに出現しやすい単語があればそれがスパムである一つの証拠となり、
スパムに現れ、非スパムにあまり現れない単語の数が多くなればスパムとしての強い証拠となる

判定は
* 判断するメールがスパムであると仮定したときにそれが観測される確率
* 判断するメールが非スパムであると仮定したときにそれが観測される確率

のどちらが高いかで行う

どの程度の確率であればスパムと判定するかは事前確率による  
スパムが多い状況なら確率が低くてもスパムと判断してもよいかも

事前確率：
* 公園にいる鳥はほとんどアヒル
 * 「ガーガー」聞こえたらほぼ間違いなくアヒル
* アヒルが観測されいない公園
 * 「ガーガー」聞こえてもそれがアヒルだと判断していいか微妙
 
のように、あらかじめ知っている(主観的)な知識の確率

ナイーブベイズでは各単語は他のすべての単語とは独立に出現するものとする  
正しい保証は無いが仮説として想定する  
それなりに精度が出る方法

## ベイズスパム分類機
